### PR TITLE
Xora 64bit

### PR DESCRIPTION
**Pull request by xXorAa**
This patch series adds 64bit support. I have tested the code on x86_64, arm64, and arm platforms as well as x86.

Under x86 it generates the same code before and after the patches in my tesing.

Under arm/arm64/x86_64 the peephole optimiser misses some optimisations but I am having dificulty finding out why. Ive narrowed it down to lines 697-704 in c68/peepm68k.c where it is checking for an instruction that moves data that is not needed.

Specically in code below it misses removing the move.l d3,d0 a I_543 

        jsr     _wrdadd
        move.l  d0,d3
        tst.l   -4120(a6)
        beq     I_543
        move.l  -4120(a6),d0
        bra     I_544
I_543:
        move.l  d3,d0
I_544:
        move.l  d0,-4132(a6)
        tst.l   -4116(a6)
        bge     I_545
        add.l   #1,432+_var
I_545:
        lea     16(a7),a7

But as it is it generates valid if slightly less optimal code.

macos support patch is huge because clang likes to complain a lot about signed/unsigned assignments/comparisons.

### CODE REVIEW

**Comment by stronnag** [comment]
Great job, nice to have no warnings from clang.

**Comment by stronnag** [comment]
Tested with a number of fairiy large projects (qtpi, perl4 with qlip and gdbm). All run as expected.

**Comment by xXorAa** [comment]
Nice, thanks for the testing. I wish I could work out the peephole optimizer problem, its probably something obvious and simple given it affects arm32 as well.

**Comment by stronnag** [comment]
No doubt we will find some 32/64 artefacts, whether they are more than cosmetic remains to be seem. This one is cosmetic.

I have an old voice-mail application (it was possibly cool in 1994). If I build with -m32, I get the following (bogus) warning:
```
"vfile.c", line 159: warning [3]: constant 0xffffffb6 not within range of type 'long'
```
and  (64bit binaries)
```
"vfile.c", line 159: warning [3]: constant 0xffffffffffffffb6 not within range of type 'long'
```
Neither warning is useful, -74 is a valid fseek (long) offset. 

```
int UpdateVoxFile(FILE *fp, FVOXREC *pvr)
{
    int n;
    
    fseek(fp, -(sizeof(FVOXREC)), SEEK_CUR); // <---------------- this is line 159-
    n = fwrite (pvr, 1, sizeof(FVOXREC), fp);
    return (n != sizeof(FVOXREC));
}   
````
The two binaries are the same size and byte for byte identical (and smaller than when last built in 2001, 89932b v. 91326b).

**Comment by xXorAa** [comment]
Ok thats an odd one, instrumenting the code its because sizeof returns an unsigned so the type ends up as unsigned long, and because it thinks its a huge number instead of negative it issues the warning.

type1 unsigned long
type2 long
Range Low ffffffff80000000
Range High 7fffffff
Signed 1-0 2-1
Value fffffffffffffff8
"test.c", line 11: warning [3]: constant 0xfffffffffffffff8 not within range of type 'long'

**Comment by xXorAa** [comment]
The "fix" for that particular case is relatively simple using stdint.h

```
diff --git a/c68/chdr.h b/c68/chdr.h
index 93d303a..fcfccf7 100644
--- a/c68/chdr.h
+++ b/c68/chdr.h
@@ -62,6 +62,8 @@
 #include <varargs.h>
 #endif /* HAS_STDARG */
 
+#include <stdint.h>
+
 /*
  *   For NON-ANSI systems.....
  */
@@ -292,7 +294,7 @@ typedef unsigned char BITSIZE;      /* size of a bitfield */
 typedef struct sblock BLOCK;   /* scope table */
 typedef enum e_bt BTYPE;       /* basic type */
 typedef unsigned char CHAR;    /* input character */
-typedef long IVAL;             /* signed integral value */
+typedef int32_t IVAL;          /* signed integral value */
 typedef unsigned int LABEL;    /* internal label */
 typedef unsigned int LEVEL;    /* scope level */
 typedef unsigned char QUALIFIER;       /* type qualifiers */
@@ -308,7 +310,7 @@ typedef struct sym SYM;             /* symbol entry */
 typedef struct stab TABLE;     /* symbol table */
 typedef enum e_sym TOKEN;      /* scanner token */
 typedef struct typ TYP;                /* type entry */
-typedef unsigned long UVAL;    /* unsigned integral value */
+typedef uint32_t UVAL; /* unsigned integral value */
 typedef struct func FUNC;      /* function entry */
 typedef struct structure STRUCT;       /* struct/union entry */
 typedef struct reg_use REGUSAGE;       /* register usage on function calls */

```

**Comment by stronnag** [comment]
> The "fix" for that particular case is relatively simple using stdint.h

Or better, the developer tele-porting back 27 years and realising that sizeof() would be unsigned and casting appropriately.
```
    fseek(fp, -((long)sizeof(FVOXREC)), SEEK_CUR);
```

**Comment by xXorAa** [comment]
The fix is probably still warranted as otherwise the compiler is issuing 64 values that don’t exist in code in error messages. I’ll give it a bit more testing then issue a PR.

**Comment by stronnag** [comment]
Perfect, thanks.

**Comment by stronnag** [comment]
Having played around with this some more, there are numerous instances in `c68/out68k*.c` where unadorned `int` or `long` is used, sometimes with `"%ld"` or "`%lu'" which results in some strange "unsigned" assembler and larger binaries from the 64bit compiler  in some cases. 

```
< ! Generated by c68 4.5 27 Feb 99 (Aug 25 2021) from "qserver.i"
---
> ! Generated by c68 4.5 27 Feb 99 (Aug 24 2021) from "qserver.i"
399c399
< 	move.l	#4294967295,I_13
---
> 	move.l	#-1,I_13
796c796
< 	move.l	#4294967295,I_13
---
> 	move.l	#-1,I_13
1475c1475,1476
< 	cmp.l	#4294967295,I_13
---
> 	move.l	#-1,d0
> 	cmp.l	I_13,d0
```

Fixing these (which I've done) together with the `chdr.h` changes means that I now get identical binaries, sizes and all the `*.s` files from both the ia32 and x86_64 compilers. 

Need to do a few more tests before PR.

Unless you've already done this as well.

**Comment by xXorAa** [comment]
I had found those as well, but I have not had time to fix them all (currently fighting c++ on OpenBMC in my $$$ job). Feel free to combine everything into one patch! I was amused that as68 read the huge numbers and converted them back to negatives without blinking :-D

**Pull request merged**
